Repository Team-Wable/WABLE-ANDROID, pull requests merged in 2024-08, with the labels that each got.

#4 #1 [FIX] : fix codeowners orga name
  github/CODEOWNERS
Labels: 🔨 [FIX], 🐱 소현

#5 [FIX:#1] : fix name .github
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/pull_request_template.md
  .github/renovate.json
  .github/workflows/develop_PR_builder.yml
Labels: 🔨 [FIX], 🐱 소현

#6 [DOCS/#1] : fix issue_template
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: 📃 [DOCS], 🐱 소현

#8 [Feature/#7] : font, color setting / data, network module redsign
  .github/CODEOWNERS
  app/build.gradle.kts
  build-logic/build.gradle.kts
  build-logic/src/main/java/com/teamwable/wable/plugin/AndroidNetworkPlugin.kt
  core/data/build.gradle.kts
  core/data/src/main/java/com/teamwable/data/di/RepositoryModule.kt
  core/data/src/main/java/com/teamwable/data/mapper/toModel/ResponseDummyDtoMapper.kt
  core/data/src/main/java/com/teamwable/data/repositoryimpl/DefaultDummyRepository.kt
  core/designsystem/.gitignore
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/AndroidManifest.xml
  core/designsystem/src/main/res/drawable/ic_launcher_background.xml
  core/designsystem/src/main/res/drawable/ic_launcher_foreground.xml
  core/designsystem/src/main/res/font/font_pretendard_regular.xml
  core/designsystem/src/main/res/font/font_pretendard_semibold.xml
  core/designsystem/src/main/res/font/pretendard_regular.otf
  core/designsystem/src/main/res/font/pretendard_semibold.otf
  core/designsystem/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  core/designsystem/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  core/designsystem/src/main/res/mipmap-hdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-mdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-xhdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/values-night/themes.xml
  core/designsystem/src/main/res/values/colors.xml
  core/designsystem/src/main/res/values/strings.xml
  core/designsystem/src/main/res/values/themes.xml
  core/designsystem/src/main/res/values/typography.xml
  core/designsystem/xml/src/main/res/values/colors.xml
  core/network/build.gradle.kts
  core/network/src/main/java/com/teamwable/network/datasource/DummyService.kt
  core/network/src/main/java/com/teamwable/network/di/NetworkModule.kt
  core/network/src/main/java/com/teamwable/network/di/Qualifier.kt
  core/network/src/main/java/com/teamwable/network/di/ServiceModule.kt
  core/network/src/main/java/com/teamwable/network/dto/request/.gitkeep
  core/network/src/main/java/com/teamwable/network/dto/response/ResponseDummyDto.kt
  core/network/src/main/java/com/teamwable/network/util/BaseResponse.kt
  core/network/src/main/java/com/teamwable/network/util/StringExt.kt
  feature/home/build.gradle.kts
  feature/main/build.gradle.kts
  feature/news/build.gradle.kts
  feature/notification/build.gradle.kts
  feature/posting/build.gradle.kts
  feature/profile/build.gradle.kts
  settings.gradle.kts
Labels: 🐱 소현, ⚙️ [SETTING]

#17 [Feature/#16] : bottom navigation
  core/common/src/main/res/drawable/ic_bnv_home_active.xml
  core/common/src/main/res/drawable/ic_bnv_home_inactive.xml
  core/common/src/main/res/drawable/ic_bnv_news_active.xml
  core/common/src/main/res/drawable/ic_bnv_news_inactive.xml
  core/common/src/main/res/drawable/ic_bnv_notification_active.xml
  core/common/src/main/res/drawable/ic_bnv_notification_inactive.xml
  core/common/src/main/res/drawable/ic_bnv_profile_active.xml
  core/common/src/main/res/drawable/ic_bnv_profile_inactive.xml
  core/ui/src/main/res/color/sel_main_bnv_menu_color.xml
  feature/main/src/main/java/com/teamwable/main/MainActivity.kt
  feature/main/src/main/res/drawable/sel_main_bnv_home.xml
  feature/main/src/main/res/drawable/sel_main_bnv_news.xml
  feature/main/src/main/res/drawable/sel_main_bnv_notification.xml
  feature/main/src/main/res/drawable/sel_main_bnv_profile.xml
  feature/main/src/main/res/layout/activity_main.xml
  feature/main/src/main/res/menu/menu_main_navigation.xml
  feature/main/src/main/res/navigation/graph_main.xml
  feature/main/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 🐱 소현

#19 [Feature/#18] : profile hamburger UI
  build-logic/src/main/java/com/teamwable/wable/plugin/AndroidFeaturePlugin.kt
  build.gradle.kts
  core/common/src/main/res/drawable/ic_profile_hamburger_btn.xml
  core/common/src/main/res/drawable/ic_share_bottomsheet_bar.xml
  core/ui/src/main/java/com/teamwable/ui/util/Constants.kt
  core/ui/src/main/res/color/sel_bottom_btn_color.xml
  core/ui/src/main/res/drawable/shape_fill_12_rect.xml
  core/ui/src/main/res/drawable/shape_fill_top_16_rect.xml
  core/ui/src/main/res/drawable/shape_gray200_line_16_rect.xml
  feature/home/src/main/res/navigation/graph_home.xml
  feature/main/src/main/java/com/teamwable/main/MainActivity.kt
  feature/main/src/main/res/menu/menu_main_navigation.xml
  feature/main/src/main/res/navigation/graph_main.xml
  feature/news/src/main/res/navigation/graph_news.xml
  feature/notification/src/main/res/navigation/graph_notification.xml
  feature/posting/src/main/res/navigation/graph_posting.xml
  feature/profile/src/main/java/com/teamwable/profile/LogoutDialogFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileDeleteConfirmFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileDeleteDialogFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileDeleteReasonFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileHamburgerBottomSheet.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileInformationFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/PushNotificationFragment.kt
  feature/profile/src/main/res/drawable/sel_profile_delete_checkbox.xml
  feature/profile/src/main/res/layout/bottomsheet_profile_hamburger.xml
  feature/profile/src/main/res/layout/fragment_delete_dialog.xml
  feature/profile/src/main/res/layout/fragment_profile.xml
  feature/profile/src/main/res/layout/fragment_profile_delete_confirm.xml
  feature/profile/src/main/res/layout/fragment_profile_delete_reason.xml
  feature/profile/src/main/res/layout/fragment_profile_information.xml
  feature/profile/src/main/res/layout/fragment_push_notification.xml
  feature/profile/src/main/res/layout/view_profile_appbar.xml
  feature/profile/src/main/res/navigation/graph_profile.xml
  feature/profile/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 💟 [UI], 🐰 언지

#21 [Setting/#15] compose designsystem
  app/src/main/java/com/teamwable/wable/WableApp.kt
  core/common/src/main/res/values/strings.xml
  core/designsystem/src/main/java/com/teamwable/designsystem/extension/SetStatusBarColor.kt
  core/designsystem/src/main/java/com/teamwable/designsystem/extension/system/SetSystemUiColor.kt
  core/designsystem/src/main/java/com/teamwable/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/teamwable/designsystem/theme/Theme.kt
  core/designsystem/src/main/java/com/teamwable/designsystem/theme/Type.kt
  core/designsystem/src/main/res/font/pretendard_regular.otf
  core/designsystem/src/main/res/font/pretendard_semibold.otf
  feature/auth/src/main/java/com/teamwable/auth/LoginScreen.kt
  feature/auth/src/main/res/values/strings.xml
  feature/main-compose/src/main/java/com/teamwable/main_compose/MainScreen.kt
Labels: ⚙️ [SETTING], 🐻 찬우

#23 [Setting/#22] datastore 모듈 세팅
  core/data/build.gradle.kts
  core/data/src/main/java/com/teamwable/data/di/RepositoryModule.kt
  core/data/src/main/java/com/teamwable/data/repository/UserInfoRepository.kt
  core/data/src/main/java/com/teamwable/data/repositoryimpl/DefaultUserInfoRepository.kt
  core/datastore/.gitignore
  core/datastore/build.gradle.kts
  core/datastore/src/main/AndroidManifest.xml
  core/datastore/src/main/java/com/teamwable/datastore/datasource/DefaultWablePreferenceDatasource.kt
  core/datastore/src/main/java/com/teamwable/datastore/datasource/WablePreferencesDataSource.kt
  core/datastore/src/main/java/com/teamwable/datastore/di/DataStoreModule.kt
  core/network/build.gradle.kts
  feature/auth/src/main/java/com/teamwable/auth/LoginScreen.kt
  feature/auth/src/main/java/com/teamwable/auth/LoginViewModel.kt
  feature/auth/src/main/java/com/teamwable/auth/model/LoginSideEffect.kt
  feature/auth/src/main/java/com/teamwable/auth/naviagation/AuthNavigation.kt
  feature/main-compose/src/main/java/com/teamwable/main_compose/MainScreen.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ⚙️ [SETTING], 🐻 찬우

#27 [Feature/#20] : news UI
  core/common/src/main/res/drawable-xhdpi/img_news_match_empty.png
  core/common/src/main/res/drawable-xxhdpi/img_news_match_empty.png
  core/common/src/main/res/drawable/ic_news_match_team_profile.xml
  core/common/src/main/res/drawable/ic_news_tag_progress_finished.xml
  core/common/src/main/res/drawable/ic_news_tag_progress_ongoing.xml
  core/common/src/main/res/drawable/ic_news_tag_progress_planned.xml
  core/common/src/main/res/drawable/ic_news_team_profile_bro.xml
  core/common/src/main/res/drawable/ic_news_team_profile_dk.xml
  core/common/src/main/res/drawable/ic_news_team_profile_drx.xml
  core/common/src/main/res/drawable/ic_news_team_profile_fox.xml
  core/common/src/main/res/drawable/ic_news_team_profile_gen.xml
  core/common/src/main/res/drawable/ic_news_team_profile_hle.xml
  core/common/src/main/res/drawable/ic_news_team_profile_kdf.xml
  core/common/src/main/res/drawable/ic_news_team_profile_kt.xml
  core/common/src/main/res/drawable/ic_news_team_profile_ns.xml
  core/common/src/main/res/drawable/ic_news_team_profile_t1.xml
  core/common/src/main/res/drawable/img_news_match_empty.png
  core/model/src/main/java/com/teamwable/model/NewsMatchModel.kt
  core/model/src/main/java/com/teamwable/model/NewsMatchScoreModel.kt
  core/model/src/main/java/com/teamwable/model/NewsRankModel.kt
  core/ui/src/main/java/com/teamwable/ui/util/CalculateTime.kt
  core/ui/src/main/res/drawable/shape_fill_2_rect.xml
  core/ui/src/main/res/drawable/shape_fill_4_rect.xml
  core/ui/src/main/res/drawable/shape_gray200_line_8_rect.xml
  core/ui/src/main/res/values/themes.xml
  feature/news/src/main/java/com/teamwable/news/NewsFragment.kt
  feature/news/src/main/java/com/teamwable/news/NewsViewModel.kt
  feature/news/src/main/java/com/teamwable/news/NewsViewPagerAdapter.kt
  feature/news/src/main/java/com/teamwable/news/match/NewsMatchAdapter.kt
  feature/news/src/main/java/com/teamwable/news/match/NewsMatchFragment.kt
  feature/news/src/main/java/com/teamwable/news/match/NewsMatchItemDecorator.kt
  feature/news/src/main/java/com/teamwable/news/match/NewsMatchScoreAdapter.kt
  feature/news/src/main/java/com/teamwable/news/match/NewsMatchScoreItemDecorator.kt
  feature/news/src/main/java/com/teamwable/news/match/NewsMatchScoreViewHolder.kt
  feature/news/src/main/java/com/teamwable/news/match/NewsMatchViewHolder.kt
  feature/news/src/main/java/com/teamwable/news/rank/NewsRankAdapter.kt
  feature/news/src/main/java/com/teamwable/news/rank/NewsRankFragment.kt
  feature/news/src/main/java/com/teamwable/news/rank/NewsRankItemDecorator.kt
  feature/news/src/main/java/com/teamwable/news/rank/NewsRankViewHolder.kt
  feature/news/src/main/res/layout/fragment_news.xml
  feature/news/src/main/res/layout/fragment_news_match.xml
  feature/news/src/main/res/layout/fragment_news_rank.xml
  feature/news/src/main/res/layout/item_news_match.xml
  feature/news/src/main/res/layout/item_news_match_score.xml
  feature/news/src/main/res/layout/item_news_rank.xml
  feature/news/src/main/res/layout/view_news_season.xml
  feature/news/src/main/res/values/strings.xml
Labels: 💟 [UI], 🐰 언지

#26 [Setting/#24] multipart setting
  core/data/src/main/java/com/teamwable/data/di/ContentResolverModule.kt
  core/data/src/main/java/com/teamwable/data/repositoryimpl/DefaultDummyRepository.kt
  core/model/src/main/java/com/teamwable/model/.gitkeep
  core/model/src/main/java/com/teamwable/model/network/Error.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/teamwable/network/util/ContentUriRequestBody.kt
  core/network/src/main/java/com/teamwable/network/util/createImagePart.kt
  core/network/src/main/java/com/teamwable/network/util/getErrorMessage.kt
  gradle/libs.versions.toml
Labels: ⚙️ [SETTING], 🐻 찬우

#29 [Feature/#28] : notification UI
  core/model/src/main/java/com/teamwable/model/NotificationActionModel.kt
  core/model/src/main/java/com/teamwable/model/NotificationInformationModel.kt
  core/ui/src/main/java/com/teamwable/ui/util/CalculateTime.kt
  core/ui/src/main/res/values/strings.xml
  feature/news/src/main/java/com/teamwable/news/rank/NewsRankAdapter.kt
  feature/news/src/main/java/com/teamwable/news/rank/NewsRankFragment.kt
  feature/notification/build.gradle.kts
  feature/notification/src/main/java/com/teamwable/notification/NotificationFragment.kt
  feature/notification/src/main/java/com/teamwable/notification/NotificationItemDecorator.kt
  feature/notification/src/main/java/com/teamwable/notification/NotificationViewModel.kt
  feature/notification/src/main/java/com/teamwable/notification/NotificationViewPagerAdapter.kt
  feature/notification/src/main/java/com/teamwable/notification/action/NotificationActionAdapter.kt
  feature/notification/src/main/java/com/teamwable/notification/action/NotificationActionFragment.kt
  feature/notification/src/main/java/com/teamwable/notification/action/NotificationActionViewHolder.kt
  feature/notification/src/main/java/com/teamwable/notification/information/NotificationInformationAdapter.kt
  feature/notification/src/main/java/com/teamwable/notification/information/NotificationInformationFragment.kt
  feature/notification/src/main/java/com/teamwable/notification/information/NotificationInformationViewHolder.kt
  feature/notification/src/main/res/layout/fragment_notification.xml
  feature/notification/src/main/res/layout/fragment_notification_vp.xml
  feature/notification/src/main/res/layout/item_notification_vp.xml
  feature/notification/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 💟 [UI], 🐰 언지

#31 [Feature/#25] : xml component
  .github/workflows/develop_PR_builder.yml
  build-logic/gradle.properties
  core/common/src/main/res/drawable/ic_home_tag_team_bro.xml
  core/common/src/main/res/drawable/ic_home_tag_team_dk.xml
  core/common/src/main/res/drawable/ic_home_tag_team_drx.xml
  core/common/src/main/res/drawable/ic_home_tag_team_fox.xml
  core/common/src/main/res/drawable/ic_home_tag_team_gen.xml
  core/common/src/main/res/drawable/ic_home_tag_team_hle.xml
  core/common/src/main/res/drawable/ic_home_tag_team_kdf.xml
  core/common/src/main/res/drawable/ic_home_tag_team_kt.xml
  core/common/src/main/res/drawable/ic_home_tag_team_ns.xml
  core/common/src/main/res/drawable/ic_home_tag_team_t1.xml
  core/common/src/main/res/drawable/ic_share_profile_img_blue.xml
  core/common/src/main/res/drawable/ic_share_profile_img_mint.xml
  core/common/src/main/res/drawable/ic_share_profile_img_purple.xml
  core/common/src/main/res/drawable/img_empty.png
  core/common/src/main/res/raw/loading_lottie.json
  core/common/src/main/res/raw/tab_lottie.json
  core/common/src/main/res/values/dimens.xml
  core/common/src/main/res/values/strings.xml
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/teamwable/ui/base/BindingDialogFragment.kt
  core/ui/src/main/java/com/teamwable/ui/component/BottomSheet.kt
  core/ui/src/main/java/com/teamwable/ui/component/LckTeamTagTextView.kt
  core/ui/src/main/java/com/teamwable/ui/component/Snackbar.kt
  core/ui/src/main/java/com/teamwable/ui/component/TwoButtonDialog.kt
  core/ui/src/main/java/com/teamwable/ui/extensions/GlideImageViewExt.kt
  core/ui/src/main/java/com/teamwable/ui/extensions/NavigationExt.kt
  core/ui/src/main/java/com/teamwable/ui/type/BottomSheetType.kt
  core/ui/src/main/java/com/teamwable/ui/type/DialogType.kt
  core/ui/src/main/java/com/teamwable/ui/type/SnackbarType.kt
  core/ui/src/main/java/com/teamwable/ui/type/TeamTag.kt
  core/ui/src/main/java/com/teamwable/ui/util/Constants.kt
  core/ui/src/main/res/drawable/sel_comment_ghost.xml
  core/ui/src/main/res/drawable/sel_feed_ghost.xml
  core/ui/src/main/res/drawable/sel_feed_heart.xml
  core/ui/src/main/res/drawable/shape_white_fill_4_rect.xml
  core/ui/src/main/res/drawable/shape_white_fill_8_rect.xml
  core/ui/src/main/res/layout/bottomsheet.xml
  core/ui/src/main/res/layout/dialog_two_button.xml
  core/ui/src/main/res/layout/item_comment.xml
  core/ui/src/main/res/layout/item_feed.xml
  core/ui/src/main/res/layout/snackbar.xml
  core/ui/src/main/res/layout/text_lck_team_tag.xml
  core/ui/src/main/res/navigation/graph_ui.xml
  core/ui/src/main/res/values/attrs.xml
  core/ui/src/main/res/values/deeplink.xml
  core/ui/src/main/res/values/strings.xml
  core/ui/src/main/res/values/styles.xml
  feature/main/src/main/java/com/teamwable/main/MainActivity.kt
  feature/main/src/main/res/navigation/graph_main.xml
  feature/profile/src/main/java/com/teamwable/profile/LogoutDialogFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileDeleteDialogFragment.kt
  gradle.properties
Labels: 💟 [UI], 🐱 소현

#33 [Feature/#32] : navigate to posting
  core/ui/src/main/java/com/teamwable/ui/extensions/NavigationExt.kt
  core/ui/src/main/res/values/deeplink.xml
  feature/home/src/main/java/com/teamwable/home/HomeFragment.kt
  feature/home/src/main/res/layout/fragment_home.xml
  feature/home/src/main/res/values/strings.xml
  feature/posting/src/main/res/navigation/graph_posting.xml
Labels: ⭐ [FEAT], 🐱 소현

#35 [Feature/#30] : posting UI
  app/src/main/AndroidManifest.xml
  core/ui/src/main/java/com/teamwable/ui/util/Constants.kt
  core/ui/src/main/res/drawable/shape_fill_20_rect.xml
  core/ui/src/main/res/values/themes.xml
  feature/news/build.gradle.kts
  feature/news/src/main/res/layout/fragment_news.xml
  feature/news/src/main/res/layout/item_news_match_score.xml
  feature/news/src/main/res/layout/item_news_rank.xml
  feature/notification/src/main/res/layout/item_notification_vp.xml
  feature/posting/src/main/java/com/teamwable/posting/PostingFragment.kt
  feature/posting/src/main/java/com/teamwable/posting/PostingViewModel.kt
  feature/posting/src/main/res/layout/fragment_posting.xml
  feature/posting/src/main/res/values/strings.xml
  feature/profile/src/main/java/com/teamwable/profile/LogoutDialogFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileDeleteConfirmFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileDeleteDialogFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileHamburgerBottomSheet.kt
  feature/profile/src/main/res/layout/fragment_delete_dialog.xml
  feature/profile/src/main/res/values/strings.xml
Labels: 💟 [UI], 🐰 언지

#36 [Feature/#34] compose component
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/teamwable/designsystem/component/button/WableButton.kt
  core/designsystem/src/main/java/com/teamwable/designsystem/component/dialog/WableButtonDialog.kt
  core/designsystem/src/main/java/com/teamwable/designsystem/component/topbar/WableTopBar.kt
  core/designsystem/src/main/java/com/teamwable/designsystem/extension/modifier/ModifierExt.kt
  core/designsystem/src/main/java/com/teamwable/designsystem/theme/Type.kt
  core/designsystem/src/main/java/com/teamwable/designsystem/type/DialogType.kt
  core/designsystem/src/main/res/values/dimens.xml
  core/designsystem/src/main/res/values/strings.xml
  feature/auth/src/main/java/com/teamwable/auth/LoginScreen.kt
  feature/auth/src/main/java/com/teamwable/auth/LoginViewModel.kt
  feature/main-compose/src/main/java/com/teamwable/main_compose/MainNavigator.kt
  feature/main-compose/src/main/java/com/teamwable/main_compose/MainScreen.kt
Labels: 🐻 찬우, COMPOSE

#38 Feature/#32 home homedetail UI
  build-logic/src/main/java/com/teamwable/wable/plugin/AndroidKotlinPlugin.kt
  build-logic/src/main/java/com/teamwable/wable/plugin/CommonConfigs.kt
  core/common/src/main/res/drawable/ic_share_logo.xml
  core/model/src/main/java/com/teamwable/model/Comment.kt
  core/model/src/main/java/com/teamwable/model/Feed.kt
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/teamwable/ui/component/LckTeamTagTextView.kt
  core/ui/src/main/java/com/teamwable/ui/component/TwoButtonDialog.kt
  core/ui/src/main/java/com/teamwable/ui/extensions/RecyclerViewDividerExt.kt
  core/ui/src/main/java/com/teamwable/ui/shareAdapter/CommentAdapter.kt
  core/ui/src/main/java/com/teamwable/ui/shareAdapter/CommentClickListener.kt
  core/ui/src/main/java/com/teamwable/ui/shareAdapter/CommentViewHolder.kt
  core/ui/src/main/java/com/teamwable/ui/shareAdapter/FeedAdapter.kt
  core/ui/src/main/java/com/teamwable/ui/shareAdapter/FeedClickListener.kt
  core/ui/src/main/java/com/teamwable/ui/shareAdapter/FeedViewHolder.kt
  core/ui/src/main/java/com/teamwable/ui/type/DialogType.kt
  core/ui/src/main/res/drawable/recyclerview_item_1_divider.xml
  core/ui/src/main/res/layout/dialog_two_button.xml
  core/ui/src/main/res/layout/item_comment.xml
  core/ui/src/main/res/layout/item_feed.xml
  core/ui/src/main/res/values/attrs.xml
  core/ui/src/main/res/values/styles.xml
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/teamwable/home/HomeDetailFragment.kt
  feature/home/src/main/java/com/teamwable/home/HomeFragment.kt
  feature/home/src/main/res/drawable/gradient_home_posting_fab.xml
  feature/home/src/main/res/layout/fragment_home.xml
  feature/home/src/main/res/layout/fragment_home_detail.xml
  feature/home/src/main/res/navigation/graph_home.xml
  feature/home/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 💟 [UI], 🐱 소현

#42 [Feature/#37] kakao login + 회원가입 + tokenInterceptor + reissue
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamwable/wable/WableApp.kt
  core/common/src/main/java/com/teamwable/common/uistate/UiState.kt
  core/common/src/main/res/drawable/ic_login_kakao.xml
  core/common/src/main/res/drawable/ic_login_kakao_btn.xml
  core/common/src/main/res/drawable/img_login_symbol.xml
  core/data/src/main/java/com/teamwable/data/di/RepositoryModule.kt
  core/data/src/main/java/com/teamwable/data/mapper/toModel/AuthMapper.kt
  core/data/src/main/java/com/teamwable/data/repository/AuthRepository.kt
  core/data/src/main/java/com/teamwable/data/repositoryimpl/DefaultAuthRepository.kt
  core/designsystem/src/main/java/com/teamwable/designsystem/theme/Color.kt
  core/model/src/main/java/com/teamwable/model/auth/UserModel.kt
  core/network/src/main/java/com/teamwable/network/Interceptor.kt
  core/network/src/main/java/com/teamwable/network/TokenInterceptor.kt
  core/network/src/main/java/com/teamwable/network/datasource/AuthService.kt
  core/network/src/main/java/com/teamwable/network/di/NetworkModule.kt
  core/network/src/main/java/com/teamwable/network/di/Qualifier.kt
  core/network/src/main/java/com/teamwable/network/di/ServiceModule.kt
  core/network/src/main/java/com/teamwable/network/dto/request/.gitkeep
  core/network/src/main/java/com/teamwable/network/dto/request/RequestSocialLoginDto.kt
  core/network/src/main/java/com/teamwable/network/dto/response/auth/ResponseReissueTokenDto.kt
  core/network/src/main/java/com/teamwable/network/dto/response/auth/ResponseSocialLoginDto.kt
  core/network/src/main/java/com/teamwable/network/util/BaseResponse.kt
  core/network/src/main/java/com/teamwable/network/util/getErrorMessage.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/teamwable/auth/LoginScreen.kt
  feature/auth/src/main/java/com/teamwable/auth/LoginViewModel.kt
  feature/auth/src/main/res/drawable-xhdpi/img_login_background.png
  feature/auth/src/main/res/drawable-xxhdpi/img_login_background.png
  feature/auth/src/main/res/drawable/img_login_background.png
  feature/auth/src/main/res/values/strings.xml
  feature/main-compose/src/main/java/com/teamwable/main_compose/MainComposeActivity.kt
  feature/main-compose/src/main/java/com/teamwable/main_compose/MainScreen.kt
  settings.gradle.kts
Labels: ⭐ [FEAT], 🐻 찬우, COMPOSE

#49 [Feature/#47] notification api
  core/data/src/main/java/com/teamwable/data/di/RepositoryModule.kt
  core/data/src/main/java/com/teamwable/data/mapper/toModel/ResponseNotificationDtoMapper.kt
  core/data/src/main/java/com/teamwable/data/repository/NotificationRepository.kt
  core/data/src/main/java/com/teamwable/data/repositoryimpl/DefaultNotificationRepository.kt
  core/network/src/main/java/com/teamwable/network/datasource/NotificationService.kt
  core/network/src/main/java/com/teamwable/network/di/ServiceModule.kt
  core/network/src/main/java/com/teamwable/network/dto/response/notification/ResponseInformationDto.kt
  core/network/src/main/java/com/teamwable/network/dto/response/notification/ResponseNotificationsDto.kt
  core/network/src/main/java/com/teamwable/network/dto/response/notification/ResponseNumberDto.kt
  feature/main/src/main/java/com/teamwable/main/MainActivity.kt
  feature/main/src/main/java/com/teamwable/main/MainViewModel.kt
  feature/notification/src/main/java/com/teamwable/notification/NotificationViewModel.kt
  feature/notification/src/main/java/com/teamwable/notification/action/NotificationActionFragment.kt
  feature/notification/src/main/java/com/teamwable/notification/information/NotificationInformationFragment.kt
  feature/notification/src/main/java/com/teamwable/notification/information/NotificationInformationViewHolder.kt
  feature/notification/src/main/res/anim/anim_swipe_refresh_slide_down.xml
  feature/notification/src/main/res/anim/anim_swipe_refresh_slide_up.xml
Labels: ⭐ [FEAT], 🐰 언지

#44 [Feature/#41] : profile UI
  core/common/src/main/res/drawable/ic_profile_badge.xml
  core/common/src/main/res/drawable/ic_profile_ghost.xml
  core/common/src/main/res/drawable/ic_profile_intro_triangle.xml
  core/common/src/main/res/drawable/ic_profile_tag_level_1.xml
  core/model/src/main/java/com/teamwable/model/Profile.kt
  core/ui/src/main/java/com/teamwable/ui/util/Constants.kt
  core/ui/src/main/res/values/styles.xml
  feature/profile/src/main/java/com/teamwable/profile/ProfileCommentListFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileFeedListFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfilePagerStateAdapter.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileTabType.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileUserType.kt
  feature/profile/src/main/res/layout/fragment_profile.xml
  feature/profile/src/main/res/layout/fragment_profile_comment.xml
  feature/profile/src/main/res/layout/fragment_profile_feed.xml
  feature/profile/src/main/res/values/strings.xml
Labels: 🐱 소현

#50 [Feature/#45] : feed api
  core/data/build.gradle.kts
  core/data/src/main/java/com/teamwable/data/di/RepositoryModule.kt
  core/data/src/main/java/com/teamwable/data/mapper/toModel/ResponseFeedDtoMapper.kt
  core/data/src/main/java/com/teamwable/data/mapper/toModel/ResponseProfileInfoDtoMapper.kt
  core/data/src/main/java/com/teamwable/data/repository/FeedRepository.kt
  core/data/src/main/java/com/teamwable/data/repository/ProfileRepository.kt
  core/data/src/main/java/com/teamwable/data/repositoryimpl/DefaultFeedRepository.kt
  core/data/src/main/java/com/teamwable/data/repositoryimpl/DefaultProfileRepository.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/teamwable/network/datasource/FeedService.kt
  core/network/src/main/java/com/teamwable/network/datasource/ProfileService.kt
  core/network/src/main/java/com/teamwable/network/di/ServiceModule.kt
  core/network/src/main/java/com/teamwable/network/dto/response/ResponseFeedDto.kt
  core/network/src/main/java/com/teamwable/network/dto/response/ResponseProfileInfoDto.kt
  core/network/src/main/java/com/teamwable/network/util/BaseResponse.kt
  core/network/src/main/java/com/teamwable/network/util/GenericPagingSource.kt
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/teamwable/ui/extensions/GlideImageViewExt.kt
  core/ui/src/main/java/com/teamwable/ui/extensions/NavigationExt.kt
  core/ui/src/main/java/com/teamwable/ui/shareAdapter/FeedAdapter.kt
  core/ui/src/main/java/com/teamwable/ui/shareAdapter/FeedViewHolder.kt
  core/ui/src/main/java/com/teamwable/ui/type/BasicProfileType.kt
  core/ui/src/main/java/com/teamwable/ui/type/ProfileUserType.kt
  core/ui/src/main/java/com/teamwable/ui/util/Constants.kt
  core/ui/src/main/java/com/teamwable/ui/util/FeedActionHandler.kt
  core/ui/src/main/res/values/deeplink.xml
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/teamwable/home/HomeDetailFragment.kt
  feature/home/src/main/java/com/teamwable/home/HomeFragment.kt
  feature/home/src/main/java/com/teamwable/home/HomeViewModel.kt
  feature/home/src/main/res/layout/fragment_home.xml
  feature/profile/build.gradle.kts
  feature/profile/src/main/java/com/teamwable/profile/ProfileFeedListFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/ProfileViewModel.kt
  feature/profile/src/main/java/com/teamwable/profile/hamburger/ProfileDeleteConfirmFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/hamburger/ProfileDeleteReasonFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/hamburger/ProfileHamburgerBottomSheet.kt
  feature/profile/src/main/java/com/teamwable/profile/hamburger/ProfileInformationFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/hamburger/PushNotificationFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/profile/ProfileCommentListFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/profile/ProfileFeedListFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/profile/ProfileFragment.kt
  feature/profile/src/main/java/com/teamwable/profile/profile/ProfilePagerStateAdapter.kt
  feature/profile/src/main/res/navigation/graph_profile.xml
  gradle/libs.versions.toml
Labels: ⭐ [FEAT], 🐱 소현

#52 [Feature/#46] : news api
  core/data/src/main/java/com/teamwable/data/di/RepositoryModule.kt
  core/data/src/main/java/com/teamwable/data/mapper/toModel/ResponseNewsDtoMapper.kt
  core/data/src/main/java/com/teamwable/data/repository/NewsRepository.kt
  core/data/src/main/java/com/teamwable/data/repositoryimpl/DefaultNewsRepository.kt
  core/model/src/main/java/com/teamwable/model/news/NewsMatchModel.kt
  core/model/src/main/java/com/teamwable/model/news/NewsMatchScoreModel.kt
  core/model/src/main/java/com/teamwable/model/news/NewsRankModel.kt
  core/network/src/main/java/com/teamwable/network/datasource/NewsService.kt
  core/network/src/main/java/com/teamwable/network/di/ServiceModule.kt
  core/network/src/main/java/com/teamwable/network/dto/response/news/ResponseGameTypeDto.kt
  core/network/src/main/java/com/teamwable/network/dto/response/news/ResponseRankDto.kt
  core/network/src/main/java/com/teamwable/network/dto/response/news/ResponseScheduleDto.kt
  feature/main/src/main/java/com/teamwable/main/MainViewModel.kt
  feature/news/src/main/java/com/teamwable/news/NewsViewModel.kt
  feature/news/src/main/java/com/teamwable/news/match/NewsMatchAdapter.kt
  feature/news/src/main/java/com/teamwable/news/match/NewsMatchFragment.kt
  feature/news/src/main/java/com/teamwable/news/match/NewsMatchScoreAdapter.kt
  feature/news/src/main/java/com/teamwable/news/match/NewsMatchScoreViewHolder.kt
  feature/news/src/main/java/com/teamwable/news/match/NewsMatchViewHolder.kt
  feature/news/src/main/java/com/teamwable/news/rank/NewsRankAdapter.kt
  feature/news/src/main/java/com/teamwable/news/rank/NewsRankFragment.kt
  feature/news/src/main/java/com/teamwable/news/rank/NewsRankViewHolder.kt
  feature/notification/src/main/java/com/teamwable/notification/action/NotificationActionFragment.kt
Labels: ⭐ [FEAT], 🐰 언지
